### PR TITLE
Review and small fixes to be discussed

### PR DESCRIPTION
**Pull request by xxthunder**
Hi @fex01 ,

First of all thank you very much for creating this role from rkoshak's ansible post. It really helped me a lot during my planned migration from openhabian to a docker-based environment on my pi4.

I did some small fixes, maybe you find them useful and worth merging into your repo.

I did not add any tests yet, sorry for that. It is definitely on my todo list.

Regards,
xxthunder

### CODE REVIEW

**Review by fex01 — APPROVED** [review]

**Review by fex01 — APPROVED** [review]
Thx, seems like that was changed since the initial creation 🤔

**Review by fex01 — COMMENTED** [review]
Just for my understanding - why skipping owner permissions and why using a capital X?

**Comment by xxthunder** [comment]
Wow, you are really fast. 😄

o means 'others', the owner is the user (u). -> https://wiki.ubuntuusers.de/chmod/

Actually I skipped 'others' because of some credentials in the configs. Nevertheless the chance that there will be other users on my openhab is rather low but you never know.

Capital X is for directories only, in case of recursive usage of chmod. I did not know that til today but that is actually a chmod feature and has nothing to do with ansible. -> https://wiki.ubuntuusers.de/chmod/#Rechte-rekursiv-setzen

**Comment by fex01** [comment]
> o means 'others', the owner is the user (u). -> https://wiki.ubuntuusers.de/chmod/

Correct, sorry brainfart from my side 😅 

> Capital X is for directories only, in case of recursive usage of chmod. I did not know that til today but that is actually a chmod feature and has nothing to do with ansible. -> https://wiki.ubuntuusers.de/chmod/#Rechte-rekursiv-setzen

And so I learned something new today 👍 

Did you test if removing `o=rx` results in any problems when deploying the openhab container? I'm not exactly sure anymore - but my initial guess would be that I did set `o=rx` to avoid trouble with openhab user != root user inside the container 🤔

**Comment by xxthunder** [comment]
> Did you test if removing `o=rx` results in any problems when deploying the openhab container? I'm not exactly sure anymore - but my initial guess would be that I did set `o=rx` to avoid trouble with openhab user != root user inside the container 🤔

Just checked: with modes 770/660 the container is still able to read those files. I guess because of root access? I am not a docker expert I must confess.

**Comment by xxthunder** [comment]
I must correct myself. You are right, removing 'others' rights is causing problems:

`2022-12-11 16:08:26.094 [WARN ] [.core.internal.folder.FolderObserver] - Error while opening file during update: /openhab/conf/things/bosch.things`

**Comment by fex01** [comment]
I thought so - the openhab service inside the container is **not** run via root but via a non-root user called openhab

**Comment by xxthunder** [comment]
Okay, fixed that for now.

**Comment by fex01** [comment]
None the less - thx for your contribution, will merge the other two pulls later / tomorrow 😊

**Comment by xxthunder** [comment]
I updated the last commit and fixed the modes. From my point of view you can merge the whole PR.

**Comment by fex01** [comment]
Almost - have a look at the original permissions, you will see that others don't get write permissions. So don't grant more permissions than necessary ;-)

**Comment by xxthunder** [comment]
But what about files openHAB creates? If the user inside the docker container is not part of openhab group, how was it ever able to create or update files?

**Comment by fex01** [comment]
I can tell you that the container will come up and work properly without granting write permissions to these three folders for 'others'. And that files will be updated and created - but I'm actually not quite sure how 😅 
If you find an explanation let me hear about it 🤔

**Comment by fex01** [comment]
Ah - wait, if you look at this task (line 41-47) you will see that the openhab user will get ownership of these folders:

```
- name: Create missing folders for repo exists
  file: 
    path: "{{ item }}"
    state: directory
    owner: "{{ openhab_user }}"
    group: "{{ openhab_user }}"
    mode: u=rwx,g=rwx,o=rx
  loop:
    - "{{ openhab_home }}/openhab/userdata/cache"
    - "{{ openhab_home }}/openhab/userdata/logs"
    - "{{ openhab_home }}/openhab/userdata/persistence"
    - "{{ openhab_home }}/openhab/userdata/tmp"
  become: True
  when: openhab_repo
```

So write permissions for the openhab service account are a non-issue, because the service account will be the owner of said files. So the real mystery remains why the dockerized openhab service fails when others have no read/execute permission 🤔

**Comment by xxthunder** [comment]
Okay, I played a bit with file modes, logged into the docker container and the files with removed access rights for 'others' are causing no problems at all. No idea what I did the first time. The user 'openhab' exists inside the container and in the system.

**Pull request merged**
